easy_admin:
    entities:
        # List the entity class name you want to manage
        Product:
            class: App\Entity\Product
        Customer:
            class: App\Entity\Customer
        Client:
            class: App\Entity\Client
            controller: App\Controller\UserAdminController
